### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xkotlin#1]
Launch Checklist

In order to launch we should:

- [x] Turn on Travis CI for the track
- [x] Add Kotlin as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] Implement at least 10 problems
- [x] Write documentation (see below)
- [x] Find a person or (ideally) a handful of people willing to check exercism regularly (daily?) to review solutions
- [x] Add track implementors and other designated code reviewers as mentors to the track. This gives you access to all the solutions in Kotlin whether or not you've submitted the problem to the site.
- [x] Add a language icon or logo (see below)
- [x] Toggle `"active"` to `true` in `config.json`
- [x] Send an email to the mailing list

## Documentation

The documentation lives in the `docs/` directory here in this repository, and gets served to the site via the x-api. It should contain at minimim:

- `INSTALLATION.md` - about how to get the language set up locally.
- `TESTS.md` - about how to run the tests for the exercises.

Some nice to haves:

- `ABOUT.md` - a short, friendly blurb about the language. What types of problems does it solve really well? What is it typically used for?
- `LEARNING.md` - a few notes about where people might want to go to learn the language from scratch.
- `RESOURCES.md` - references and other useful resources.

## Logo/Icon

We try to create a language icon that has the exercism colors, and is recognizably similar to the language icon. Sometimes this isn't possible due to copyright issues. See http://exercism.io/languages for all the existing icons.

The logo should live under `/public/img/tracks/` in the exercism/exercism.io repository.
https://github.com/exercism/exercism.io/tree/master/public/img/tracks

Attribution goes in https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md

If image assets are not your strong suit, just find a reasonable image to start from, along with the information about the licensing, and we'll figure out the colorization thing (I've written some scripts to help me do this part).

Some icons are the official language logo (tweaked). Where a language doesn't seem to have an official logo, or where the official logo has copyright issues, we just make something up.

## Successful Launches

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The code reviews do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore aspects of the language. Referencing existing blog posts and style guides seems to work well, when making specific recommendations.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by sdavids13** [comment]
I added 10 problems via PR #5

**Comment by sdavids13** [comment]
I snagged the Java documentation since it's nearly 100% applicable and made minor changes pretty much just `s/java/kotlin/g` in: https://github.com/exercism/xkotlin/commit/5cd3b18f3e33cf54c34552c3afb4e8c278a4fb33

**Comment by kytrinyx** [comment]
perfect!

**Comment by sdavids13** [comment]
@kytrinyx I added 7 more exercises and the logo is now merged in - can you please update the main site's submodule reference to the latest commit? Out of curiosity, how often do you all push out the changes to the live site? It would be nice to try a dry-run before going "live".

As for finding volunteers for the track, do you have suggestions finding volunteers? Do you just generally look for volunteers from the community via mailing lists, reddit channels, etc? Then do we just provide our github user ids and you will add them to the list?

Finally, after some volunteers are identified how long until the track is activated?

**Comment by kytrinyx** [comment]
The languages page is showing the logo.

I deploy the exercises API more or less every day (when traveling it's harder, because I don't want to just deploy and get on a plane, in case something goes badly wrong).

I deployed the x-api with new exercises earlier today, this is what is up: http://x.exercism.io/v3/tracks/kotlin

You can test exercises by saying `exercism fetch kotlin EXERCISE`. I'll make sure that you have access to all submissions, if anyone chooses to submit these before the track goes live.

Let me know if you want me to tweet something out about beta-testing the track.

**Comment by sdavids13** [comment]
I tried the first couple and they all seem to work fine. I created 11 more modules, so when they are pushed out to the live site maybe you can go ahead and tweet it (perhaps mention we are looking for reviewers).

Side note: is there a recommended ordering for the modules? I have just been going in alphabetical order but thought there may be a suggested ordering based on the level of difficulty of the problem. If so, do you mind ordering it based on your preference?

**Comment by kytrinyx** [comment]
The ordering should be roughly based on the difficulty level (order in config will be the order that people get the exercises). It's not too important to get it just right, we can adjust it down the road if we see that some people are having particular trouble with an exercise or whatever.

I'll update the API now and tweet about wanting beta testers for this.

**Comment by sdavids13** [comment]
Can you add me as a track reviewer? I only see other people's submissions that I have submitted myself.

**Comment by kotp** [comment]
The same thing happens for me.

You can download the exercises, and submit the solution for each.  You can use the example.rb one if you want.  It doesn't really matter.  Some of the ones I have submitted are archived, because they were just solved to get review access on those.

**Comment by sdavids13** [comment]
I added 5 more modules and reordered the modules based on relative complexity - primarily by just mimicking other track's ordering. Is this track good to launch without having multiple designated reviewers?

**Comment by kytrinyx** [comment]
@sdavids13 I thought I did add you as a reviewer on Kotlin, let me double-check that.

**Comment by kytrinyx** [comment]
Yeah, you're listed as track mentor, and you have the correct ACLs. There may just not be any solutions for the other exercises.

**Comment by sdavids13** [comment]
@kytrinyx I think this track is good to go - I just toggled the config to activate the module. Will you send out an email to the mailing list, or would you like me to do it? If you want me to do it, what mailing list ;)

**Comment by kytrinyx** [comment]
I send out a newsletter every Sunday... ish. https://tinyletter.com/exercism I'll be sending it out tomorrow. Last week I missed it, because I spoke at OSCON and Self.Conference back to back and didn't have it in me to write anything up.

**Comment by kotp** [comment]
The last check mark is checkable now, since the tinyletter went out today.
